language: node_js
install:
  - npm install
script:
  - npm run build
after_success:
  - nvm run deploy
env:
  global:
    - secure: UfU5XpK0Rv7Vk1vPHDgAvmovVIpQTMyzDMHSJKfl54ZW/TxfNuUjVep/YyBVIBcehRSSmcHJ3TnsBV3CJlWtV2vzS7kJW/E2qLiQBNZHI3L6HO7SdTSYkPP0o2R4xeBVO5DkxiQJy5VCne+WBIRfEJUaPMgct2UXcSrCVK3btfBypYPGH5bCU8snpLeZTzpNwUcOFVkL8P8vfPgLMplLfywAWT5Ph1PHTvQdpIjlYla0XXQz9ffqMQ90HkpLnWlRMMBtP2EXQx7tSdDK58L+whmjxTMs0ldWLnfTH2Xg0ir2OoZn2KLkdnhwuHWZmv+IL70EnXGPFhSrkOHxfW/gTZGPnr2ddxIeIUMhm+Jhww5dDoa/ptARw54pG8eJwYTuIsM25fK4BQLkVIsGHUtVhW8zRJ+Lq73JRROusIVOu4cG6gL1pafSuCM7K8gwaSELldhgWKzgFqQRekIFNsHJw7pM5XLetLxV07yMJs8ViwDgukMMca6D2xhUZ0EXw6jBsiR63UtXl3ODf2xwPlmrWObkXRxRBrVo2Sgerl+cnAjO/pOlZh9Zo3Z4NPoUo9xgT/TPDiNd9eeWpCCqZZ8XdN6MgEfqqeTk7anBYdK6nsxjW0RPiZQWZW+cqcCncnjqWFABqlqGd9dGc3f/fBTtml083XOqEHkr4fBP97GmhvI=
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
