# name of file MUST be 'config.yml'
baseURL: http://immigrantswelcome.github.io
siteMetaTitle: Immigrants Welcome!
campaignTitle: Immigrants Welcome!
email: email@fightforthefuture.org
pressEmail: press@fightforthefuture.org
pressPhone: null
copyright: A project of Fight for the Future. No copyright intended.
privacy: Privacy statement here
donateUrl: https://www.fightforthefuture.org
facebookPage: https://www.facebook.com/fightfortheftr/
# modals
thanksTitle: Thanks for adding your voice to defend immigrants.
thanksText: Share this page with your friends and family to spread the word.
thanksFBButton: share on facebook
thanksTWButton: share on twitter
thanksStoryButton: add your story
storyTitle: Add your story
storySubmit: add your story
signupTitle: Join the campaign
signupSubmit: join the campaign
# form placeholders
signupPlaceholderFirstName: First name
signupPlaceholderLastName: Last name
signupPlaceholderEmail: Email
signupPlaceholderZip: Zip code
storyPlaceholderFirstName: First name
storyPlaceholderLastName: Last name
storyPlaceholderEmail: Email address
storyPlaceholderZip: Zip code
storyPlaceholderYear: Year of immigration
storyPlaceholderOrigin: Where did you or your family immigrate from?
storyPlaceholderWhy: >
    Tell us the story of why you or your family immigrated to the United States? Consider
    starting with “I came to the United States…” or “My family came to the United States…”
storyPlaceholderPhoto: >
    Add a link to a photo of you or members of your family who immigrated—consider imgur.com to
    host your image.
# story page buttons
storyPageStoryButton: add your story
storyPageCampaignButton: join the campaign
# API
signupIdentifier: 0
storyIdenfifier: 0
# dev
DEBUG: false