# name of file MUST be 'config.yml'
baseURL: http://immigrantswelcome.github.io
siteMetaTitle: Immigrants Welcome!
campaignTitle: Immigrants Welcome!
email: email@fightforthefuture.org
pressEmail: press@fightforthefuture.org
pressPhone: null
copyright: A project of Fight for the Future. No copyright intended.
privacy: Privacy statement here
donateUrl: https://www.fightforthefuture.org
facebookPage: https://www.facebook.com/fightfortheftr/
# modals
thanksTitle: Thanks for adding your voice to defend immigrants.
thanksText: Share this page with your friends and family to spread the word.
thanksFBButton: share on facebook
thanksTWButton: share on twitter
thanksStoryButton: add your story
storyTitle: Add your story
storySubmit: add your story
signupTitle: Join the campaign
signupSubmit: join the campaign
# story page buttons
storyPageStoryButton: add your story
storyPageCampaignButton: join the campaign
# API
signupIdentifier: 0
storyIdenfifier: 0
# dev
DEBUG: false