# name of file MUST be 'config.yml'
baseURL: http://immigrantswelcome.github.io
siteMetaTitle: Immigration is America
email: email@fightforthefuture.org
pressEmail: press@fightforthefuture.org
pressPhone: +1 508 474 5248
copyright: A project of Fight for the Future. No copyright intended.
privacyUrl: https://www.fightforthefuture.org
donateUrl: https://www.fightforthefuture.org
facebookPage: https://www.facebook.com/fightfortheftr/
# API
signupIdentifier: 0
storyIdenfifier: 0
# dev
DEBUG: false