# name of file MUST be 'config.yml'
baseURL: http://immigrantswelcome.github.io
siteMetaTitle: Immigrants Welcome!
campaignTitle: Immigrants Welcome!
email: email@fightforthefuture.org
pressEmail: press@fightforthefuture.org
pressPhone: null
copyright: A project of Fight for the Future. No copyright intended.
privacy: Privacy statement here
donateUrl: https://www.fightforthefuture.org
facebookPage: https://www.facebook.com/fightfortheftr/
# API
signupIdentifier: 0
storyIdenfifier: 0
# dev
DEBUG: false