#!/bin/bash

set -o errexit -o nounset

if [ "$TRAVIS_BRANCH" != "master" ]
then
  echo "This commit was made against the $TRAVIS_BRANCH and not the master! No deploy!"
  exit 0
fi

rev=$(git rev-parse --short HEAD)

cd dist

git
# need to setup a new user for building!
git init
git config user.name "immigrantswelcome-bot"
git config user.email "immigrantswelcome-bot@fightforthefuture.com"

git remote add upstream "https://$GH_TOKEN@github.com/immigrantswelcome/immigrantswelcome.github.io.git"
git fetch upstream
git reset upstream/gh-pages

# any other build stuff?

touch .

git add -A .
git commit -m "rebuild pages at ${rev}"
git push -q upstream HEAD:gh-pages
