#!/bin/bash

set -o errexit -o nounset

if [ "$TRAVIS_PULL_REQUEST" != "false" ]
then
    echo "This is a PR and not a commit! No deploy!"
    exit 0
fi

if [ "$TRAVIS_BRANCH" != "development" ]
then
  echo "This commit was made against the $TRAVIS_BRANCH and not the development! No deploy!"
  exit 0
fi

echo "This commit is eligible for deployment."

rev=$(git rev-parse --short HEAD)

echo "working on ${rev}, moving into dist"
cd dist

# git
echo "init git"
git init
echo "init git user"
git config user.name "immigrantswelcome-bot"
git config user.email "immigrantswelcome-bot@users.noreply.github.com"

echo "init git remote"
git remote add upstream "https://$GH_TOKEN@github.com/immigrantswelcome/immigrantswelcome.github.io.git"
echo "git fetch"
git fetch upstream
echo "git reset"
git reset upstream/master

# any other build stuff?

echo "mark all as fresh"
touch .

echo "add all to git"
git add -A .

echo "git status"
git status

echo "git commit ${rev}"
git commit -m "rebuild pages at ${rev}"

# lets test this first
echo "push"
#git push -q upstream HEAD:master
