#!/bin/bash

chokidar 'src/icons/*.svg' -c 'npm run icons' --initial &
chokidar 'src/html/**/*.html' 'db/**/*' -c 'npm run build' --initial &
browser-sync start --no-online --no-open --no-ghost-mode --no-ui --no-notify --server "dist" --files \
    'src/css/**/*.css' \
    'src/images/**/*' \
    'src/icon_sprite/sprite.svg'
