#!/bin/bash

chokidar 'src/icons/*.svg' -c './scripts/build_icons' --initial &
chokidar 'src/html/**/*.html' 'db/**/*' -c './scripts/build' --initial &
browser-sync start --no-online --no-open --no-ghost-mode --no-ui --no-notify --server "dist" --files \
    'src/static/**/*'
